local MoldyReforgeTooltip = Moldy:NewModule("ReforgeTooltip", "AceEvent-3.0")

local REFORGE_TABLE_BASE = 112
local REFORGE_TABLE = {
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_SPIRIT_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_DODGE_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_PARRY_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_HIT_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_CRIT_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
    {ITEM_MOD_HASTE_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_EXPERTISE_RATING_SHORT, ITEM_MOD_MASTERY_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_SPIRIT_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_DODGE_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_PARRY_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_HIT_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_CRIT_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_HASTE_RATING_SHORT},
    {ITEM_MOD_MASTERY_RATING_SHORT, ITEM_MOD_EXPERTISE_RATING_SHORT},
}

function MoldyReforgeTooltip:OnEnable()
    local _SetHyperlink = GameTooltip.SetHyperlink
    function GameTooltip:SetHyperlink(link)
        local reforgeId, value = link:match("^reforge:(.*):(.*)$")
        if not reforgeId or not value then
            return _SetHyperlink(self, link)
        end

        reforgeId, value = tonumber(reforgeId), tonumber(value)
        local reforge = REFORGE_TABLE[reforgeId - REFORGE_TABLE_BASE]
        if not reforge then return nil end

        self:ClearLines()
        self:AddLine("Reforged", 1, 1, 1)
        self:AddDoubleLine(reforge[1], string.format("-%s", value), nil, nil, nil, 1.0, 0.125, 0.125)
        self:AddDoubleLine(reforge[2], string.format("+%s", value), nil, nil, nil, 0.125, 1.0, 0.125)
        self:Show()
    end
end
